### ISSUE TITLE
Problema ao Visualizar a Tela do Cliente

### ISSUE THREAD

**Issue by tdssolucoes** [OpenSourceCommunityBrasil/Aegys-Acesso-Remoto#51]
Ao acessar o cliente verifiquei que click no ícone da pasta e não funcionava, coloquei como cliente meu notebook (uma maquina ao lado da outra) verifiquei que vejo o ponteiro do mouse na minha maquina em cima do ícone da pasta, No entanto, quando vejo no notebook(Cliente) vejo que o ponteiro do mouse esta em outra posição da tela, por isso quando click na funciona.

resumo: O Ponteiro do mouse visualizado não esta sincronizado com cliente, verifiquei que a resolução do cliente(notebook) , não fica a mesma quando faço acesso), achei que poderia ter alguma relação

**Comment by mobius1qwe** [comment]
Esse problema ocorre também quando o recurso de mostrar rastro do mouse tá ativo?

**Comment by tdssolucoes** [comment]
Esse problema ocorre também quando o recurso de mostrar rastro do mouse tá
ativo?
*SIM*

Acho que é uma coisa relacionado a resolução



Em seg., 21 de fev. de 2022 às 13:15, Mobius One ***@***.***>
escreveu:
