### ISSUE TITLE
Freeze at "Awaiting autehntication", and nothing happens.

### ISSUE THREAD

**Issue by YordanYanakiev** [OpenSourceCommunityBrasil/Aegys-Acesso-Remoto#53]
I am trying to connect, but it freeze at "Awaiting autehntication". 
Did someone fix this ?
and what is the cause ?
![image](https://user-images.githubusercontent.com/6534199/172335461-c4ef9624-a215-4827-aaf8-176fa8388e15.png)

**Comment by YordanYanakiev** [comment]
is this the reason the project to be abandoned ?

**Comment by mobius1qwe** [comment]
Project isn't abandoned, the quick adjustments for it to work were done, now the more complex features are being developed which takes time. About the error, which server you did you point in the config?

**Comment by YordanYanakiev** [comment]
I am using the server which is in the project.
It works once or twice, and then it stall like this.

**Comment by mobius1qwe** [comment]
so you're using your own compiled server? Did you point that in the uConstants unit or in the server address box under config page?

**Comment by YordanYanakiev** [comment]
Yes, I did. As I have mentioned - it is working 1, 2 times, and then - this.

**Comment by mobius1qwe** [comment]
So, it works once or twice and then it stops working. During these reworks did you restart the client application or not? If not it's a known issue #43.

**Comment by YordanYanakiev** [comment]
Restarting the client application doesnt fix the issue. Only when the server is restarted then the issue gone.
It's likely that it is the server somewhat.

**Comment by mobius1qwe** [comment]
Duplicated issue #43
